-- ==========================================================
-- Smart Car Recommendation System
-- Database Schema
-- ==========================================================
--
-- Database Name:
-- smart_car_recommendation_system
--
-- Main Table:
-- cars
--
-- Columns:
-- Brand
-- Model
-- Body_Type
-- Price_Min_Lakh
-- Price_Max_Lakh
-- Price_Avg_Lakh
-- Price_INR
-- Mileage_Min_kmpl
-- Mileage_Max_kmpl
-- Mileage_Avg_kmpl
-- Engine_Min_CC
-- Engine_Max_CC
-- Engine_Avg_CC
-- Safety_Rating
-- Safety_Rating_Available
-- NCAP_Body
-- Fuel_Type_Primary
-- Fuel_Type_Full
-- Transmission_Primary
-- Transmission_Full
-- Seating_Min
-- Seating_Max
--
-- Note:
-- The backend connects to MySQL using SQLAlchemy
-- and automatically seeds the 'cars' table from
-- cars_in.csv if it does not already exist.